ALL_OUT_DIR: converge_files
CONTINUITY: 85
COVERAGE: 85
FILTERFRAGMENTS: 0.5
GENE_COUNT: 2000
GENOMES: /data/jrusso/roadies-datasets/gzipped_flies
GROUP_CSV: group_file.csv
IDENTITY: 65
IDENTITY_DEEP: 40
LENGTH: 500
MASKSITES: 0.02
MAX_DUP: 10
NUM_INSTANCES: 8
OUT_DIR: output_files
REFERENCE: null
SCORES: HOXD55.q
STEPS: 1
SUPPORT_THRESHOLD: 0.95
UPPER_CASE: 0.9
